apiVersion: v1
kind: ServiceAccount
metadata:
  name: eve-corp-api-reader
  namespace: eve-corp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-eve-corp-api-reader
  namespace: eve-corp
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-eve-corp-api-reader
  namespace: eve-corp
subjects:
  - kind: ServiceAccount
    name: eve-corp-api-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-eve-corp-api-reader
