apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eve-seat-pvc
  namespace: eve-corp
spec:
  storageClassName: glusterfs
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi